[profile.default]
solc = "0.8.25"
src = "contracts"
out = "out"
libs = ["lib"]
"viaIR"= true
"optimizerSteps"="u"


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options


remappings = ["@openzeppelin/=lib/openzeppelin-contracts/","@chainlink/=node_modules/@chainlink/"]